name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v2

      - name: ChromeDriver Kurulumu
        run: |
          sudo apt-get update
          sudo apt-get install -y libappindicator3-1 fonts-liberation
          sudo apt-get install -y google-chrome-stable
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          rm chromedriver_linux64.zip
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Python ve bağımlılıkları kur
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Selenium testlerini çalıştır
        run: |
          source venv/bin/activate
          pytest tests/

      - name: Test sonrası temizlik
        run: |
          sudo apt-get remove -y google-chrome-stable
          sudo apt-get autoremove -y
